
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 18 23:43:08 CST 2023
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ESP_CONJER = 17;
  public static final int INTERROGACION = 10;
  public static final int GUION = 7;
  public static final int CONJUNTO = 19;
  public static final int OR = 2;
  public static final int FLECHA = 8;
  public static final int DOS_PUNTOS = 6;
  public static final int ID_CONJER = 15;
  public static final int EOF = 0;
  public static final int ASTERISCO = 9;
  public static final int CONCA = 4;
  public static final int error = 1;
  public static final int LLAVE_C = 12;
  public static final int DELIMITADOR = 13;
  public static final int ECOM_EXP = 16;
  public static final int LLAVE_A = 11;
  public static final int PUNTO_COMA = 5;
  public static final int RESERVADA = 18;
  public static final int NOMBRES = 14;
  public static final int MAS = 3;
}

